project:
  name: ramdemo-aws-vpc
  owner: ramakrishna.thandra@gmail.com
  package_lambda: false
  regions:
    - us-east-1
    - eu-west-1
  s3_bucket: ''
  reporting: true
tests:
  vpc-public-all-possible-regions:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      CreateAdditionalPrivateSubnets: 'false'
      CreateNATGateways: 'false'
      CreatePrivateSubnets: 'false'
      NumberOfAZs: '2'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
      - us-east-1
      - eu-west-1
    s3_bucket: ''
    template: templates/aws-vpc.template.yaml
  vpc-private-all-possible-regions:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      CreateAdditionalPrivateSubnets: 'false'
      CreatePublicSubnets: 'false'
      CreateNATGateways: 'false'
      NumberOfAZs: '2'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
      - us-east-1
      - eu-west-1
    s3_bucket: ''
    template: templates/aws-vpc.template.yaml
